version: "3.9"
services:
  app:
    container_name: restapi-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: "docker"
    depends_on:
      - database
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/code

  database:
    image: ubuntu/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      TZ: "UTC"